export const quizConfig = [
  {
    question: 'Для кого вы ищете учебное заведение?',
    step: 1,
    type: 'radio',
    listSelector: 'quiz-form__radio-buttons',
    inputs: [
      {
        label: 'Себе',
        name: 'for',
        value: 'self',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
      {
        label: 'Родственнику',
        name: 'for',
        value: 'relative',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
      {
        label: 'Ребенку',
        name: 'for',
        value: 'child',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
      {
        label: 'Супругу/супруге',
        name: 'for',
        value: 'spouse',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
      {
        label: 'Коллеге',
        name: 'for',
        value: 'colleague',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
      {
        label: 'Другое',
        name: 'for',
        value: 'else',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
    ],
  },
  {
    question: 'В каком городе планируете поступать?',
    inputTitle: 'Город',
    step: 2,
    type: 'select',
    listSelector: 'select__options',
    inputs: [
      {
        label: 'Москва',
        name: 'city',
        value: 'moscow',
        type: 'radio',
        classes: {
          wrapper: 'option',
          label: 'option__label',
          input: 'option__input',
        },
      },
      {
        label: 'Санкт-Петербург',
        name: 'city',
        value: 'saint-petersburg',
        type: 'radio',
        classes: {
          wrapper: 'option',
          label: 'option__label',
          input: 'option__input',
        },
      },
      {
        label: 'Новосибирск',
        name: 'city',
        value: 'novosibirsk',
        type: 'radio',
        classes: {
          wrapper: 'option',
          label: 'option__label',
          input: 'option__input',
        },
      },
      {
        label: 'Нижний новгород',
        name: 'city',
        value: 'nizhny-novgorod ',
        type: 'radio',
        classes: {
          wrapper: 'option',
          label: 'option__label',
          input: 'option__input',
        },
      },
      {
        label: 'Казань',
        name: 'city',
        value: 'kazan',
        type: 'radio',
        classes: {
          wrapper: 'option',
          label: 'option__label',
          input: 'option__input',
        },
      },
      {
        label: 'Екатеринбург',
        name: 'city',
        value: 'ekaterinburg',
        type: 'radio',
        classes: {
          wrapper: 'option',
          label: 'option__label',
          input: 'option__input',
        },
      },
      {
        label: 'Любой',
        name: 'city',
        value: 'any',
        type: 'radio',
        classes: {
          wrapper: 'option',
          label: 'option__label',
          input: 'option__input',
        },
      },
    ],
  },
  {
    question: 'Какое образование уже есть?',
    step: 3,
    type: 'radio',
    listSelector: 'quiz-form__radio-buttons',
    inputs: [
      {
        label: '9 классов',
        name: 'current',
        value: 'self',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
      {
        label: '11 классов',
        name: 'current',
        value: 'relative',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
      {
        label: 'Училище',
        name: 'current',
        value: 'child',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
      {
        label: 'Колледж/техникум',
        name: 'current',
        value: 'spouse',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
      {
        label: '11 классов',
        name: 'current',
        value: 'colleague',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
      {
        label: 'Неоконченное высшее',
        name: 'current',
        value: 'else',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
    ],
  },
  {
    question: 'Куда планируете поступать?',
    step: 4,
    type: 'radio',
    listSelector: 'quiz-form__radio-buttons',
    inputs: [
      {
        label: 'Вуз',
        name: 'target',
        value: 'university',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
      {
        label: 'Колледж/техникум',
        name: 'target',
        value: 'college',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
      {
        label: 'Училище',
        name: 'target',
        value: 'school',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
    ],
  },
  {
    question: 'Какую форму обучения предпочитаете?',
    step: 5,
    type: 'radio',
    listSelector: 'quiz-form__radio-buttons',
    inputs: [
      {
        label: 'Очную',
        name: 'format',
        value: 'full-time',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
      {
        label: 'Заочную',
        name: 'format',
        value: 'part-time',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
      {
        label: 'Дистанционную',
        name: 'format',
        value: 'distance',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
    ],
  },
  {
    question: 'Рассматриваете платное обучение?',
    step: 6,
    type: 'radio',
    listSelector: 'quiz-form__radio-buttons',
    inputs: [
      {
        label: 'Нет, только бюджет',
        name: 'payment',
        value: 'free',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
      {
        label: 'Да, планирую учиться платно',
        name: 'payment',
        value: 'paid',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
      {
        label: 'Возможны оба варианта',
        name: 'payment',
        value: 'any',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
    ],
  },
  {
    question: 'Какая специальность интересует?',
    inputTitle: 'Специальность',
    step: 7,
    type: 'select',
    listSelector: 'select__options',
    inputs: [
      {
        label: 'Философия',
        name: 'direction',
        value: 'philosophy',
        type: 'radio',
        classes: {
          wrapper: 'option',
          label: 'option__label',
          input: 'option__input',
        },
      },
      {
        label: 'Социология',
        name: 'direction',
        value: 'sociology',
        type: 'radio',
        classes: {
          wrapper: 'option',
          label: 'option__label',
          input: 'option__input',
        },
      },
      {
        label: 'Экономика',
        name: 'direction',
        value: 'economy',
        type: 'radio',
        classes: {
          wrapper: 'option',
          label: 'option__label',
          input: 'option__input',
        },
      },
      {
        label: 'Юриспурденция',
        name: 'direction',
        value: 'jurisprudence',
        type: 'radio',
        classes: {
          wrapper: 'option',
          label: 'option__label',
          input: 'option__input',
        },
      },
      {
        label: 'Медицина',
        name: 'direction',
        value: 'medicine',
        type: 'radio',
        classes: {
          wrapper: 'option',
          label: 'option__label',
          input: 'option__input',
        },
      },
      {
        label: 'Любая',
        name: 'direction',
        value: 'any',
        type: 'radio',
        classes: {
          wrapper: 'option',
          label: 'option__label',
          input: 'option__input',
        },
      },
    ],
  },
  {
    question: 'Как скоро планируете поступать?',
    step: 8,
    type: 'radio',
    listSelector: 'quiz-form__radio-buttons',
    inputs: [
      {
        label: 'Как можно быстрее',
        name: 'time',
        value: 'now',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
      {
        label: 'Квартал',
        name: 'time',
        value: 'quarter',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
      {
        label: 'Год',
        name: 'time',
        value: 'year',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
      {
        label: 'Месяц',
        name: 'time',
        value: 'month',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
      {
        label: 'Полгода',
        name: 'time',
        value: 'half-year',
        type: 'radio',
        classes: {
          wrapper: 'radio-button',
          label: 'radio-button__label',
          input: 'radio-button__input',
        },
      },
    ],
  },
  {
    question: 'Ваша подборка готова! 🥳 Куда нам отправить её?',
    step: 9,
    type: 'submit',
    listSelector: 'submit-form__inputs',
    inputs: [
      {
        label: '',
        name: 'userName',
        value: '',
        type: 'text',
        placeholder: 'Как вас зовут?',
        classes: {
          wrapper: 'text-input',
          label: 'text-input__label',
          input: 'text-input__input',
        },
      },
      {
        label: '',
        name: 'phone',
        value: '',
        type: 'tel',
        placeholder: 'Номер телефона',
        classes: {
          wrapper: 'text-input',
          label: 'text-input__label',
          input: 'text-input__input',
        },
      },
      {
        label: '',
        name: 'email',
        value: '',
        type: 'email',
        placeholder: 'E-mail',
        classes: {
          wrapper: 'text-input',
          label: 'text-input__label',
          input: 'text-input__input',
        },
      },
    ],
  },
];
